### ISSUE TITLE
broken because of missing dependency

### ISSUE THREAD

**Issue by akhanf** [jordandekraker/Hippocampal_AutoTop#13]
This is now breaking hippunfold because `bc` is not in the autotop container -- @jordandekraker  can you revert this back or replace with something that doesn't use `bc`? (is a pain to rebuild new containers..)

We should make sure we test any new changes inside the container too to ensure the same environment..

https://github.com/jordandekraker/Hippocampal_AutoTop/blob/d96d0f0f58bf8efb9e1f9964cdc7afa3dc74128f/tools/ANTsTools/runAntsLabelMaps_SynOnly.sh#L85

**Comment by akhanf** [comment]
btw I've rolled it back for my testing, so no rush on this

**Comment by jordandekraker** [comment]
I reverted this commit for now, but this really should get committed and added to the singularity container - the current `if then` statement does not actually work and so all labels are being used in multicontrast label-label registration

I'm leaving this thread open to remind us to add `bc` next singularity build.

**Comment by jordandekraker** [comment]
Fixed with @royhaast 's pull request!
