### ISSUE TITLE
singularity image testing

### ISSUE THREAD

**Issue by jordandekraker** [jordandekraker/Hippocampal_AutoTop#24]
Something seems to be missing in the singleSubject singularity image. It runs on graham, but nowhere else.

`/src/mcr_v97/run_singleSubject.sh: 1: eval: /src/mcr_v97/singleSubject: not found`

When I shell into the container, this file exists. Maybe a permissions or PATH issue, or perhaps singularity version. Not solved by removing $SINGULAIRTY_OPTS, and I haven't been able to identify any other relevant differences between graham and other PC environments.

**Comment by akhanf** [comment]
I'm no longer building any Hippocampal_AutoTop containers on circleci since the khanlab fork isn't being used anymore. The only containers are khanlab/autotop_deps and khanlab/hippunfold.  You should be able to use the autotop_deps container with something like this:
```
SINGULARITYENV_AUTOTOP_DIR=path_to_your_cloned_repo singularity exec docker://khanlab/autotop_deps:latest path_to_run_singleSubject.sh
```

**Comment by jordandekraker** [comment]
Thanks. Looks like it was caused by a broken MCR compile, rebuilding following 3a3bf147b69bff7fc402f9f2b6d1ad92546083e9 seemed to do the trick.

Tested and working again.
