### ISSUE TITLE
Ali merging TODOs

### ISSUE THREAD

**Issue by jordandekraker** [jordandekraker/Hippocampal_AutoTop#3]
I didn't want to make a separate issue for each (since it'll probably be just me working on them), so I'm copying some notes and TODOs from Ali's singularity support fork merge here (will comment as notes are addressed):

OK, have a working singularity version now -- tested on 100307 hcp subject and results look great! Had to make some changes, but mostly minor and things should still work without the container (only non-backwards compatible change is the AUTOTOP_DIR requirement). But we can first iron out some things (see TODO's below) and add documentation for building/running the container before doing a merge-squash.. Also you should make sure things work for you (compiling, building, running) first too..
Can be run with:
singularity run --nv NAME_OF_IMG <in_file> <out_dir>

Current version of the container can be found here:
/scratch/akhanf/autotop_2020_06_17.sif

build process:

need to run compile.m with Matlab R2019b to compile the matlab code, then run sudo singularity build NAME_OF_OUTPUT.sif Singularity to build the container
in the container, the repository is placed in /src
TODO: try miniconda instead to make smaller image
TODO: make CPU version of recipe too
TODO: make Dockerfile versions and push to dockerhub
paths

For getting paths to dependent files, I couldn't get it to work by changing dir or getting path of file because of MCR, so I opted to require a new environment variable for this. Now, AUTOTOP_DIR must be set to the root folder of this repository. In the singularity recipe, this is already taken care of, but for running outside the container the user will now have to set this variable in their login scripts or before running, but I think this is reasonable
niftynet

had to upgrade to niftynet 0.6 to resolve some dependencies in the container, Yingli helped with this
because of this, the name of niftynet output file seemed to change, so I updated the script to read the output filename from inferred.csv instead of hardcoding it again (so hopefully should be backwards compatible, but should test that!)
niftynet required the model folder to be writable, so now copying to the hipp's tmp/ folder before running - TODO: remove this folder after running?
singleSubject_mcr.m

I made this separate version that doesn't call addpath(), but just realized there is a better way:
TODO: find the matlab command that checks whether it is in a MCR or not, so we can just use singleSubject.m for both versions..
atlases:

I made tar files of the CIT and UPenn_ExVivo folders, and put them in a dropbox
When building these are then downloaded into the corresponding location in the container /src/atlases

**Comment by jordandekraker** [comment]
adding TODO: add support for singularity call including optional manual segmentation image

**Comment by jordandekraker** [comment]
TODO: find the matlab command that checks whether it is in a MCR or not, so we can just use singleSubject.m for both versions..
DONE

TODO: add support for singularity call including optional manual segmentation image
DONE: this was already the case, but should add some documentation

TODO: make CPU version of recipe too
DONE: Current version runs on CPU when no GPU is present, but raises a warning and requires the --nv flag. I'm leaving this in for now as this will be required to run additional UNet training (eg. fine-tuning) which may be needed in future releases

**Comment by akhanf** [comment]
btw I fixed some things in the dockerfile and testing it out now..

**Comment by jordandekraker** [comment]
These issues have all been addressed here and in the below repos. Closing this issue.
https://github.com/khanlab/hippunfold
https://github.com/khanlab/autotop_deps

Specifically, support for manual labels is offered throughout now. Pipeline is now running via docker using a single call, works whether GPU or CPU, and is bootstrapped from miniconda to keep the size down.
